apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: 192.168.189.131:5000/front-end:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8079
        env:
        - name: NODE_ENV
          value: "production"
        - name: CATALOGUE_HOST
          value: "catalogue"
        - name: USER_HOST
          value: "user"
        - name: PAYMENT_HOST
          value: "payment"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - port: 80
      targetPort: 8079
      protocol: TCP
      nodePort: 30090
